### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by krolaw** [gumo-py/datastore-viewer#14]
$ export DATASTORE_VIEWER_HOST=127.0.0.1
$ export DATASTORE_VIEWER_PORT=8082
$ datastore-viewer
Traceback (most recent call last):
  File "/home/krolaw/.local/bin/datastore-viewer", line 4, in <module>
    from datastore_viewer import DatastoreViewer
  File "/home/krolaw/.local/lib/python2.7/site-packages/datastore_viewer/__init__.py", line 15
    emulator_host: Optional[str] = None,
                 ^
SyntaxError: invalid syntax

This may be because, during installation:
flasgger 0.9.3 has requirement jsonschema<3.0.0, but you'll have jsonschema 3.2.0 which is incompatible.

Running Ubuntu 19.10

**Comment by akiray03** [comment]
@krolaw Thank you for your inquiry.

datastore-viewer only supports versions newer than Python 3.7.
If necessary, install and try with Python 3.7.

If the problem continues, please contact us again.

**Comment by krolaw** [comment]
$ python3 --version
Python 3.7.5

**Comment by krolaw** [comment]
@akiray03, ok reinstalled with pip3:

$ export DATASTORE_VIEWER_HOST=127.0.0.1
$ export DATASTORE_VIEWER_PORT=8082
$ datastore-viewer 
Traceback (most recent call last):
  File "/home/krolaw/.local/bin/datastore-viewer", line 8, in <module>
    DatastoreViewer().run(
  File "/home/krolaw/.local/lib/python3.7/site-packages/datastore_viewer/__init__.py", line 21, in __init__
    raise RuntimeError(f'Environment variable "DATASTORE_EMULATOR_HOST" is required.')

**Comment by akiray03** [comment]
@krolaw Sorry for the inconvenience caused by the lack of a README description.

Please set the IP and port number of the Cloud Datastore Emulator to the environment variable DATASTORE_EMULATOR_HOST.

README was updated with #15.

If the problem continues, please contact us again.

**Comment by krolaw** [comment]
Ok, working, thanks.

**Comment by akiray03** [comment]
Thank you for your feedback 😄
